Feature/set-up
Hope1226/react-bookstore pull request #1
Opened 2021-12-06 23:30 UTC by Hope1226

In this feature branch I:
- Set up reactjs
- Removed boilerplate
- Added books component 
- Added categories component
- Added Nav component 
- Added router

2021-12-06 23:51 UTC, Hope1226 commented
**Note to the code reviewer** _I forgot to set up linters initially before setting up the app, I guess that is why GitHub action is not checking for linters. I have checked the code for linters locally no error or warning was given. I would appreciate it if you could consider this while reviewing this PR. Thank you in advance._

2021-12-07 00:13 UTC, omar-labana requested changes
Hi @Hope1226, 

Excellent work so far! 👌
You have implemented almost all the required features. ✔️ 
There are some cases that you need to adjust but you are almost done! 😀

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-07 00:13 UTC, omar-labana commented on src/components/Books.js
> +        ))}
- [ ]  Kindly, create a new `Button` component then update the Books component to make use of it then pass the book data as a prop. This will make it a bit easier when invoking redux action in the next milestones.

2021-12-07 00:49 UTC, Hope1226 commented on src/components/Books.js
> +        ))}
Hi @omar-labana, Thank you for your feedback! I would really appreciate it if you could be a bit more clear about `Button` component, what is it supposed to be used for? `bookList` obj is just added for demonstration and for making the layout, the props will definitely be used in the next milestones, please let me know if you insist on this change. Also, I really could not find anything about `Button` component in the requirement.

2021-12-07 05:32 UTC, omar-labana commented on src/components/Books.js
> +        ))}
@Hope1226 My apologies Hope, I mistyped `Button` instead of `Book`.

2021-12-07 07:55 UTC, Hope1226 commented on src/components/Books.js
> +        ))}
@omar-labana Thanks a lot for your clarification, above is well noted and will be addressed accordingly

2021-12-07 11:50 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @Hope1226,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-07 11:55 UTC, merged